### DISCUSSION TITLE
I cannot extract the TypedHeader<Host> using http2

### DISCUSSION THREAD

**Discussion by philippgl** [tokio-rs/axum#1916] [Q&A]
- [x] I have looked for existing issues (including closed) about this

### Version 

24f8dc5 (head)

### Platform

Linux lab-phgl 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux

### Crates

Cargo.tom:
```toml
[package]
name = "example-bug"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { path = "../../axum", features = ["headers", "http2" ] }
tokio = { version = "1.0", features = ["full"] }
```

### Description

I cannot extract the host header (I have not tried other headers), if using http2. i needed to use `--http2-prior-knowledge` or https (using the axum-server crate).

```sh
curl --http2 --http2-prior-knowledge -v 'http://localhost:3000/'
```
 works, but

```sh
curl --http2 --http2-prior-knowledge -v 'http://localhost:3000/host'
```
breaks.

I tried this code:

```rust
use std::net::SocketAddr;

use axum::{extract::TypedHeader, headers::Host, routing::get, Router};

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/host", get(host_handler))
        .route("/", get(|| async { "static reply" }));
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let server = axum::Server::bind(&addr);
    server.serve(app.into_make_service()).await.unwrap();
}

async fn host_handler(TypedHeader(host): TypedHeader<Host>) -> String {
    format!("connected to {}", host.hostname())
}
```

I expected to see this happen: 

With the above curl command, I expect:

```
connected to localhost
```
(status 200)

Instead, this happened: 

```
Header of type `host` was missing
```
(status 400)
