### DISCUSSION TITLE
How to shutdown tokio runtime when handler panics?

### DISCUSSION THREAD

**Discussion by lightsing** [tokio-rs/axum#2078] [Q&A] [answered]
I'm using the 'fail-fast' approach in my code, but I found that panic happens in handler does not cause the whole program shutdown.
Even my tokio runtime is configured using `unhandled_panic` api in `tokio-unstable`:
```rust
    tokio::runtime::Builder::new_multi_thread()
        .unhandled_panic(UnhandledPanic::ShutdownRuntime)
        .enable_all()
        .build()
        .unwrap()
        .block_on(async_main())
```
The version of axum I used is rev `b80d1261377a59d7a498f1f3b8f8d160e1c61d9e` from git.
rustc version: `rustc 1.70.0-nightly (0c61c7a97 2023-03-25)`
other deps are:
```toml
tokio = { version = "1.28", features = ["sync", "macros", "rt-multi-thread"] }
tower-http = { version = "0.4", features = ["full"] }
```
