### DISCUSSION TITLE
Trouble with CatchPanicLayer for panic handling

### DISCUSSION THREAD

**Discussion by pyama2000** [tokio-rs/axum#2108] [Q&A] [answered]
## Overview
I added `tower_http::catch_panic::CatchPanicLayer` to handle panics, but it's not working as expected, and panics are still occurring. How can I implement it properly to handle panics with `CatchPanicLayer`?

## Dependencies

```toml
[dependencies]
axum = "0.6.19"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.2", features = ["catch-panic"] }
```

## Codes

```rust
use axum::routing::get;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let app = axum::Router::new()
        .route("/panic", get(|| async { panic!("panic!!") }))
        .layer(tower_http::catch_panic::CatchPanicLayer::new());
    axum::Server::bind(&"0.0.0.0:8080".parse()?)
        .serve(app.into_make_service())
        .await?;
    Ok(())
}
```

## Results

when making a request using curl as shown below:

```shell
curl http://127.0.0.1:8080/panic
```

The application produced the following error:

```
thread 'tokio-runtime-worker' panicked at 'panic!!', src/main.rs:6:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 3
fish: Job 1, 'cargo run --release' terminated by signal SIGABRT (Abort)
```

In my understanding, I expected the application to return an HTTP status code 500 without crashing when encountering a panic. I apologize if my code implementation was incorrect.
