### DISCUSSION TITLE
How to pass State and Form into a handler at the same time?

### DISCUSSION THREAD

**Discussion by upk1997** [tokio-rs/axum#2531] [Q&A] [answered]
### Summary

I'm a Rust newbie and it's the first time I use axum.

I would like to receive POST forms and do something like password checking with the app state which stores password hashes. When I pass Form and State at the same time, the compiler shows these message that I cannot understand:
```
the trait bound `fn(State<AppState>, Form<ApiLoginForm>) -> impl Future<Output = Result<Response<Body>, axum::http::StatusCode>> {api_login}: Handler<_, _>` is not satisfied
the following other types implement trait `Handler<T, S>`:
  <axum_extra::handler::or::Or<L, R, Lt, Rt, S> as Handler<(M, Lt, Rt), S>>
  <axum_extra::handler::IntoHandler<H, T, S> as Handler<T, S>>
  <Layered<L, H, T, S> as Handler<T, S>>
  <MethodRouter<S> as Handler<(), S>>
```

Here's my code in function `main`:
```Rust
// prepare users & sessions
let app_state = state::AppState {
    users: Arc::new(Mutex::new(user::from_database(&database).await?)),
    sessions: Arc::new(Mutex::new(session::from_database(&database).await?)),
};

let app = Router::new()
    .route("/login", post(user::handler::api_login))
    .with_state(app_state.clone());
```

The handler `api_login` and some associated structs:
```Rust
#[derive(Serialize)]
#[serde(default, rename_all = "camelCase")]
pub struct ApiLoginResponse {
    success: bool,
    message: Option<String>,
}

#[derive(Serialize)]
#[serde(default, rename_all = "camelCase")]
pub struct ApiLoginForm {
    uid: Option<String>,
    password: Option<String>,
}

pub async fn api_login(
    State(app_state): State<state::AppState>,
    Form(form): Form<ApiLoginForm>,
) -> Result<Response, StatusCode> {
    println!(
        "Get form\n[uid] {:?}\n[password] {:?}",
        form.uid, form.password
    );

    let response_data = ApiLoginResponse {
        success: true,
        message: None,
    };

    Ok(Json(response_data).into_response())
}
```

I tried `middleware::from_fn_with_state` as well, but it still doesn't work.

Dependencies:
```toml
[dependencies]
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["cookie"] }
chrono = "0.4.31"
reqwest = "0.11.22"
serde = "1.0.192"
serde_derive = "1.0.190"
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
tokio-stream = "0.1.14"
memory-stats = "1.0.0"
tower-http = { version = "0.5.1", features = ["fs"] }
firestore = { version = "0.39.0" }
```

Did I miss any important steps, or am I using a combination of dependencies with incompatible versions?

Thanks.

### axum version

0.7.4
