### DISCUSSION TITLE
how to call `fallback` when `.nest_service` does not match

### DISCUSSION THREAD

**Discussion by cppcoffee** [tokio-rs/axum#2791] [Q&A] [answered]
### Version

```shell
% cargo tree | grep axum
├── axum v0.6.20
│   ├── axum-core v0.3.4
├── axum-core v0.3.4 (*)
├── axum-extra v0.7.7
│   ├── axum v0.6.20 (*)
│   ├── axum-core v0.3.4 (*)
```

### Crates

```toml
axum = { version = "0.6", default-features = false, features = [ "http1", "json", "query", "headers", "ws", "multipart" ] }
axum-extra = { version = "0.7" }
axum-core = "0.3.4"
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
```

### Description

To have axum call a `fallback` when there is no matching path, simply call the `fallback` function. However, when `.nest_service` does not match, it responds with a 404 and does not call the `fallback`. How can this issue be resolved?

```rust
let app = Router::new().nest_service("/", ServeDir::new("/www")).fallback(fallback)
```

I thought of using axum middleware to handle this, but I don't know how to read the body?

Is there any other way?

### axum version

v0.6.20
