### DISCUSSION TITLE
from_fn_with_state does not compile

### DISCUSSION THREAD

**Discussion by harshRn** [tokio-rs/axum#3353] [Q&A] [answered]
Hi, 
Picked up the guide from here:
https://docs.rs/axum/latest/axum/middleware/fn.from_fn_with_state.html

I want to understand why this does not work the way it has been described in the page:

My middleware

```rust
pub async fn middleware(
    State(state): State<AppState>,
    session: Session,
    mut request: Request,
    next: Next,
) -> Response {
   /* do something */
    next.run(request).await
}
```

my usage:

```rust
.layer(axum::middleware::from_fn_with_state(
    shared_state.clone(),
    middleware
))
```

AppState:

```rust
struct AppState {
    snippets: Model
}
```

```rust
#[derive(Clone)]
pub struct Model {
    pool: Pool<MySql>,
}

```

The error I get:

```
error[E0277]: the trait bound `axum::middleware::FromFn<fn(State<AppState>, tower_sessions::Session, axum::http::Request<Body>, Next) -> impl Future<Output = Response<Body>> {authenticate}, Arc<AppState>, Route, _>: tower_service::Service<axum::http::Request<Body>>` is not satisfied
   --> src/routes.rs:60:20
    |
60  |               .layer(axum::middleware::from_fn_with_state(
    |  ______________-----_^
    | |              |
    | |              required by a bound introduced by this call
61  | |                 shared_state.clone(),
62  | |                 authenticate,
63  | |             )) // since this uses session it needs to be work after the session layer
    | |_____________^ unsatisfied trait bound
    |
    = help: the trait `tower_service::Service<axum::http::Request<Body>>` is not implemented for `FromFn<fn(..., ..., ..., ...) -> ... {authenticate}, ..., ..., ...>`
    = help: the following other types implement trait `tower_service::Service<Request>`:
              axum::middleware::FromFn<F, S, I, (T1, T2)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6, T7)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6, T7, T8)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6, T7, T8, T9)>
            and 8 others
note: required by a bound in `Router::<S>::layer`
  
    |
303 |     pub fn layer<L>(self, layer: L) -> Router<S>
    |            ----- required by a bound in this associated function
...
306 |         L::Service: Service<Request> + Clone + Send + Sync + 'static,
    |                     ^^^^^^^^^^^^^^^^ required by this bound in `Router::<S>::layer`
```

**Comment by jplatte** [comment]
Have you tried <https://docs.rs/axum/latest/axum/attr.debug_middleware.html>?

**Reply by harshRn** [reply]
just did, and unfortunately, I am seeing the same error I am having trouble making sense of. I am very new to axum:
```
error[E0277]: the trait bound `axum::middleware::FromFn<fn(State<AppState>, tower_sessions::Session, axum::http::Request<Body>, Next) -> impl Future<Output = Response<Body>> {middleware::middleware}, Arc<AppState>, Route, _>: tower_service::Service<axum::http::Request<Body>>` is not satisfied
   --> src/routes.rs:60:20
    |
60  |   ...   .layer(axum::middleware::from_fn_with_state(
    |  ________-----_^
    | |        |
    | |        required by a bound introduced by this call
61  | | ...       shared_state.clone(),
62  | | ...       middleware,
63  | | ...   )) // since this uses session it needs to be work after...
    | |_______^ unsatisfied trait bound
    |
    = help: the trait `tower_service::Service<axum::http::Request<Body>>` is not implemented for `FromFn<fn(..., ..., ..., ...) -> ... {authenticate}, ..., ..., ...>`
    = help: the following other types implement trait `tower_service::Service<Request>`:
              axum::middleware::FromFn<F, S, I, (T1, T2)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6, T7)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6, T7, T8)>
              axum::middleware::FromFn<F, S, I, (T1, T2, T3, T4, T5, T6, T7, T8, T9)>
            and 8 others
note: required by a bound in `Router::<S>::layer`
   --> /Users/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/axum-0.8.3/src/routing/mod.rs:306:21
    |
303 |     pub fn layer<L>(self, layer: L) -> Router<S>
    |            ----- required by a bound in this associated function
...
306 |         L::Service: Service<Request> + Clone + Send + Sync + 's...
    |                     ^^^^^^^^^^^^^^^^ required by this bound in `Router::<S>::layer
    ```

**Reply by jplatte** [reply]
Without more info, it's impossible to tell what the issue is. Could you

- share your `Cargo.toml`
- show the imports of the types involved (i.e. the paths you imported `State`, `Session`, `Request`, `Next`, `Response` from)
- try to comment out the part you omitted (`/* do something */`)

**Reply by harshRn** [reply]
Ofc, thank you for your time :
Cargo.toml
```toml
[package]
name = "snippetbox-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
askama = "0.13.0"
axum = { version = "0.8.3", features = ["macros"] }
axum-extra = "0.10.1"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
bcrypt = "0.17.0"
bytes = "1.10.1"
chrono = "0.4.40"
clap = { version = "4.5.35", features = ["derive"] }
console-subscriber = "0.4.1"
env_logger = "0.11.7"
futures = "0.3.31"
http-body-util = "0.1.3"
log = "0.4.27"
normalize-path = "0.2.1"
regex = "1.11.1"
serde = "1.0.219"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "mysql", "chrono"] }
thiserror = "2.0.12"
time = "0.3.41"
tokio = { version = "1.44.1", features = ["full", "tracing"] }
tower = { version = "0.5.2", features = ["timeout"] }
tower-http = { version = "0.6.2", features = ["full"] }
tower-sessions = "0.14.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["mysql"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
validator = { version = "0.20.0", features = ["derive"] }
```

my imports:

```rust
use crate::{
    AppState,
    handlers::{home, snippet_create, snippet_create_post, snippet_view},
};
use axum::middleware::from_fn;
use axum::{
    Router,
    extract::MatchedPath,
    http::Request,
    routing::{get, post},
};
use std::sync::Arc;
use time::Duration;
use tower_http::timeout::TimeoutLayer;
use tower_sessions::cookie::SameSite;
// for trailing slash routes
//https://github.com/tokio-rs/axum/issues/1118
use axum_extra::routing::RouterExt;
use tower_http::{catch_panic::CatchPanicLayer, services::ServeDir, trace::TraceLayer};
use tower_sessions::{Expiry, SessionManagerLayer};
```


```rust
#[derive(Clone)]
struct AppState {
    snippets: models::snippet::SnippetModel,
    users: models::users::UserModel,
}

#[derive(Clone)]
struct Authenticated {
    val: bool,
}

impl AppState {
    pub fn server_error(e: Box<dyn std::error::Error>) -> Response {
        (
            StatusCode::INTERNAL_SERVER_ERROR,
            format!("Internal server error : {}", e),
        )
            .into_response()
    }

    pub fn render(render_result: Result<String, Error>) -> Response {
        // let mut header = HeaderMap::new();
        // this error where CONTENT_LENGTH is being given a non-numerical value
        // is not being caught at compile time or run-time
        // external client like curl does point towards the error
        // header.insert(CONTENT_LENGTH, "content length".parse().unwrap());
        match render_result {
            Ok(html) => (StatusCode::OK, Html(html)).into_response(),
            Err(err) => {
                AppState::server_error(Box::new(err));
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "Template rendering error",
                )
                    .into_response()
            }
        }
    }

    pub async fn is_authenticated(ext_state: Extension<Arc<Authenticated>>) -> bool {
        let auth = ext_state.val;
        println!("is_authenticated: {} ", auth);
        if auth { true } else { false }
    }
}
```


middleware:
```rust
#[axum::debug_middleware]
pub async fn authenticate(
    State(state): State<AppState>,
    session: Session,
    mut request: Request,
    next: Next,
) -> Response {
    let auth_res: Result<Option<i32>, tower_sessions::session::Error> =
        session.get("authenticatedUserID").await;
    let id;
    if let Ok(id_opt) = auth_res {
        if let Some(rid) = id_opt {
            id = rid;
        } else {
            return next.run(request).await;
        }
    } else {
        return next.run(request).await;
    }
    println!("id is : {}", id);
    let exists = state.users.exists(id).await;
    if let Err(e) = exists {
        return AppState::server_error(Box::new(e));
    }
    let exists = exists.unwrap();
    if exists {
        request.extensions_mut().insert(Authenticated { val: true }); // vibe coded line of code. CHANGE
    } else {
        request
            .extensions_mut()
            .insert(Authenticated { val: false }); // vibe coded line of code. CHANGE
    }

    next.run(request).await
}
```
