### DISCUSSION TITLE
Bump `matchit` to 0.8.6 to support special chars in paths

### DISCUSSION THREAD

**Discussion by kriswuollett** [tokio-rs/axum#3382] [General]
Perhaps we can reopen #2128 since `matchit` now seems to support colons in the paths, e.g., `/things/{id}:ping`, for patterns like in https://google.aip.dev/136? Proof of concept is in #3381.

**Comment by mladedav** [comment]
See #3143 and more specically the linked issue #3140 and the upstream issue in [matchit](https://github.com/ibraheemdev/matchit/issues/67).

It's true that this got delayed quite a bit, you might want to check with matchit if they want some help with 0.9.

However, if you just want to use `:` and `*` inside your paths, I think that that might already work, you just need to [turn off v0.7 checks](https://docs.rs/axum/latest/axum/struct.Router.html#method.without_v07_checks) and I believe you might have to use percent-encoding in the routes.

**Comment by kriswuollett** [comment]
Ok. I had tried turning off the v0.7 checks today and just tried percent encoding now, but I still get the panic `Invalid route "/feeds/{id}:refresh": Only one parameter is allowed per path segment`. Started looking at web APIs again after only just using gRPC for a while..

My code looks more or less like:

```rust
pub fn router(foo: api::AnyFoo) -> Router<()> {
    Router::new()
        .without_v07_checks()
        .route("/", get(default_route))
        .nest("/v1", v1::router(foo))
}

// ...

mod v1 {
    pub fn router(foo: api::AnyFoo) -> Router<()> {
        Router::new()
            .without_v07_checks()
            .route("/", get(default_route))
            .route("/feeds", post(create_feed))
            .route("/feeds/{id}%3Arefresh", post(refresh_feed))
            .with_state(FooState { foo })
    }

    // ...
}
```

**Reply by mladedav** [reply]
Matchit does not allow partial matches in the version we're using, but that's something the linked issue is about.

I though you wanted just to use a colon inside a segment, not do partial match. We'll have to wait for upstream support (or help development there).

**Reply by kriswuollett** [reply]
I just noticed that I forgot to push the changes to the workspace manifest and lock file in https://github.com/tokio-rs/axum/pull/3381. The example code compiles and works. And if you revert the change in the linked `matchit` version, then it panics. The `{id}:method` style now works in my own code if I pull in the branch with:

```toml
[patch.crates-io]
axum = { git = "https://github.com/kriswuollett/axum", branch = "matchit-colon-paths" }
axum-core = { git = "https://github.com/kriswuollett/axum", branch = "matchit-colon-paths" }
axum-macros = { git = "https://github.com/kriswuollett/axum", branch = "matchit-colon-paths" }
```

So... I think this usage of `:` may just be held up by the current `matchit` version in https://github.com/tokio-rs/axum/issues/3140 that you referred me to. But I haven't tested all rfc3986 `sub-delims`.
