### DISCUSSION TITLE
How to print more log?

### DISCUSSION THREAD

**Discussion by lz1998** [tokio-rs/axum#563] [Q&A] [answered]
```rust
pub async fn list_dataset(Json(req): Json<ListDatasetRequest>) -> Result<Json<ListDatasetResponse>, StatusCode>
```

I have written a handler, and I run the server on my Macbook. It works.

However, when I compose it with nginx, it doesn't work. How to print more log? I want to know what request body is before deserializing.

`Failed to parse the request body as JSON: EOF while parsing a value at line 1 column 0%`

**Comment by davidpdrsn** [comment, marked as answer]
Try this https://github.com/tokio-rs/axum/blob/main/examples/print-request-response/src/main.rs

**Reply by lz1998** [reply]
I copy the code and some errors occurs.
```bash
error[E0277]: the trait bound `impl Future: IntoResponse` is not satisfied
  --> src/bin/server.rs:27:10
   |
27 |         .layer(
   |          ^^^^^ the trait `IntoResponse` is not implemented for `impl Future`
   |
   = note: required because of the requirements on the impl of `Service<Request<hyper::Body>>` for `HandleError<AndThen<AsyncFilter<Route, fn(Request<hyper::Body>) -> impl Future {map_request}>, fn(Response<http_body::combinators::box_body::UnsyncBoxBody<axum::body::Bytes, axum::Error>>) -> impl Future {map_response}>, [closure@src/bin/server.rs:29:46: 34:18], hyper::Body>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `lab_mt_ops` due to previous error

```

**Reply by lz1998** [reply]
Here is my code.

https://github.com/lz1998/atest

Cargo.toml
```toml
[package]
name = "atest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.3.4"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
tower = { version = "0.4", features = ["util", "filter"] }
hyper = { version = "0.14", features = ["full"] }
```

src/main.rs
```rust
//! Run with
//!
//! ```not_rust
//! cargo run -p example-print-request-response
//! ```

use axum::{
    body::{Body, BoxBody, Bytes},
    error_handling::HandleErrorLayer,
    http::{Request, Response, StatusCode},
    routing::post,
    Router,
};
use std::net::SocketAddr;
use tower::{filter::AsyncFilterLayer, util::AndThenLayer, BoxError, ServiceBuilder};

#[tokio::main]
async fn main() {
    // Set the RUST_LOG, if it hasn't been explicitly defined
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var(
            "RUST_LOG",
            "example_print_request_response=debug,tower_http=debug",
        )
    }
    tracing_subscriber::fmt::init();

    let app = Router::new()
        .route("/", post(|| async move { "Hello from `POST /`" }))
        .layer(
            ServiceBuilder::new()
                .layer(HandleErrorLayer::new(|error| async move {
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        format!("Unhandled internal error: {}", error),
                    )
                }))
                .layer(AndThenLayer::new(map_response))
                .layer(AsyncFilterLayer::new(map_request)),
        );

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::debug!("listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn map_request(req: Request<Body>) -> Result<Request<Body>, BoxError> {
    let (parts, body) = req.into_parts();
    let bytes = buffer_and_print("request", body).await?;
    let req = Request::from_parts(parts, Body::from(bytes));
    Ok(req)
}

async fn map_response(res: Response<BoxBody>) -> Result<Response<Body>, BoxError> {
    let (parts, body) = res.into_parts();
    let bytes = buffer_and_print("response", body).await?;
    let res = Response::from_parts(parts, Body::from(bytes));
    Ok(res)
}

async fn buffer_and_print<B>(direction: &str, body: B) -> Result<Bytes, BoxError>
    where
        B: axum::body::HttpBody<Data = Bytes>,
        B::Error: Into<BoxError>,
{
    let bytes = hyper::body::to_bytes(body).await.map_err(Into::into)?;
    if let Ok(body) = std::str::from_utf8(&bytes) {
        tracing::debug!("{} body = {:?}", direction, body);
    }
    Ok(bytes)
}
```
