### DISCUSSION TITLE
I import reqwest and the size of binary increase

### DISCUSSION THREAD

**Discussion by lz1998** [tokio-rs/axum#864] [Q&A] [answered]
I import reqwest and do nothing else.

Run `cargo build --release`, and I found the size of binary is 274KB larger.

```bash
With reqwest

lz1998@lizhengdeMacBook-Pro ~/C/r/t/release (master)> ll                                                                                                                                                                                                                      (base) 
total 1800
drwxr-xr-x   68 lz1998  staff   2.1K Mar 17 01:55 build
drwxr-xr-x  513 lz1998  staff    16K Mar 17 01:57 deps
drwxr-xr-x    2 lz1998  staff    64B Mar 17 01:31 examples
drwxr-xr-x    2 lz1998  staff    64B Mar 17 01:31 incremental
-rwxr-xr-x    1 lz1998  staff   892K Mar 17 01:57 rs_test
-rw-r--r--    1 lz1998  staff   108B Mar 17 01:31 rs_test.d


Without reqwest
lz1998@lizhengdeMacBook-Pro ~/C/r/t/release (master)> ll                                                                                                                                                                                                                      (base) 
total 1248
drwxr-xr-x   68 lz1998  staff   2.1K Mar 17 01:55 build
drwxr-xr-x  480 lz1998  staff    15K Mar 17 01:56 deps
drwxr-xr-x    2 lz1998  staff    64B Mar 17 01:31 examples
drwxr-xr-x    2 lz1998  staff    64B Mar 17 01:31 incremental
-rwxr-xr-x    1 lz1998  staff   618K Mar 17 01:56 rs_test
-rw-r--r--    1 lz1998  staff   108B Mar 17 01:31 rs_test.d
```

main.rs
```rust
use axum::{response::Html, routing::get, Router};
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    // build our application with a route
    let app = Router::new().route("/", get(handler));

    // run it
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    println!("listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn handler() -> Html<&'static str> {
    Html("<h1>Hello, World!</h1>")
}
```

Cargo.toml
```toml
[package]
name = "rs_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4"
tokio = { version = "1.0", features = ["full"] }
# reqwest = "0.11"

[profile.release]
opt-level = 'z'
debug = false
lto = true
incremental = false
codegen-units = 1
strip = true
```
