### ISSUE TITLE
No method named `into_service` found for struct `axum::Router` in the current scope

### ISSUE THREAD

**Issue by michaelmerrill** [tokio-rs/axum#1480]
### Version
```bash
axum v0.6.0-rc.2
axum-core v0.3.0-rc.2
```
### Platform
```bash
Darwin x.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```
### Crates
```toml
cfg-if = "0.1.2"
worker = "0.0.11"
console_error_panic_hook = { version = "0.1.1", optional = true }
axum = { version = "0.6.0-rc.2", default-features = false }
futures-executor = "0.3.24"
http = "0.2.8"
tower-service = "0.3.2"
```

### Description

I'm new to Rust so this is most likely user error. I am using the `simple-router-wasm` example to implement a router in Cloudflare Workers. I'm unable to access the method `into_service()` as it says it's out of scope.

```rust
use tower_service::Service; // unused import: `tower_service::Service`

#[event(fetch)]
pub async fn main(req: Request, env: Env, _ctx: worker::Context) -> Result<Response> {
    log_request(&req);

    utils::set_panic_hook();

    // TODO: Convert Request -> HttpRequest
    let request: HttpRequest<String> = HttpRequest::builder()
        .uri("https://serverless.example/api/")
        .body("Some Body Data".into())
        .unwrap();

    let response: AxumResponse = block_on(app(request));

    // TODO: Convert AxumResponse -> Response
    Response::ok("Ok")
}

async fn app(request: HttpRequest<String>) -> AxumResponse {
    let router = AxumRouter::new()
        .route("/", get(|| async { "Hi!" }))
        .into_service(); // no method named `into_service` found for struct `axum::Router` in the current scope

    let response = router.call(request).await.unwrap();
    response
}
```

I'm also running into an issue with compiling for wasm where the `socket2` crate seems to be causing issues. I've pushed up my repo [here](https://github.com/michaelmerrill/workers-axum) if you'd like to try it.
