### ISSUE TITLE
`extract::Path` doesn't work with types using `serde::Deserializer::deserialize_any`

### ISSUE THREAD

**Issue by paolobarbolini** [tokio-rs/axum#1678]
### Motivation

`PathDeserializer` doesn't support `deserialize_any` [^1] so it doesn't work with things like `time::Date` [^2]

### Proposal

Add support for `deserialize_any`. I might be able to look into it in the following days.

### Alternatives

Create a wrapper around the type and force it to use a specific deserializer

[^1]: https://github.com/tokio-rs/axum/blob/87a80ec47bfd2c39ac4ea3d1acffb5d1ff540f63/axum/src/extract/path/de.rs#L59
[^2]: https://github.com/time-rs/time/blob/d97594b9f5cfeab0335c16687e26a8b51c56a526/time/src/serde/mod.rs#L124

**Comment by davidpdrsn** [comment]
What would such an implementation look like? Afaik URL params aren't a self describing format so when you encounter some key/value pair how do you know what to serialize that into?

**Comment by jplatte** [comment]
I think _if_ we support it, `deserialize_str` is the right implementation.

**Comment by paolobarbolini** [comment]
`serde_urlencoded` fowards it to `deserialize_map` and it seems to work
https://github.com/nox/serde_urlencoded/blob/d8bc15d16adf6b3ba6ae46d199d7109cf5079efa/src/de.rs#L102

The playground doesn't enable the right time features for it to work, but you can test it locally:

## Cargo.toml

```toml
[package]
name = "test123"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
time = { version = "0.3", features = ["serde-human-readable", "parsing"] }
serde_urlencoded = "0.7"
```

## main.rs

```rust
use serde::Deserialize;
use time::Date;

fn main() {
    #[derive(Debug, Deserialize)]
    struct Stuff {
        date: Date,
    }

    let deserialized: Stuff = serde_urlencoded::from_str("date=2022-01-01").unwrap();
    println!("{deserialized:?}");
}
```

## stdout

```
Stuff { date: 2022-01-01 }
```
