### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lcmgh** [tokio-rs/axum#1724]
I spotted a memory leak in my Kubernetes hosted application. Please note that Kubernetes shows the real occupied memory of a program (total memory - available memory (not free)). 

1. Changing the memory allocator to Microsoft's Mimalloc made the app decrease memory sometimes while it is still increasing over time
2. Base image: Google Distroless (Debian)

So I tried to create a minimal reproducable example on my local machine and at least the Mac OS Activity monitor shows an increase of memory even when all requests stopped.

### Reproduce

Prerequisities:

* `cargo install oha`
* Project code from below

1. Run program and measure memory usage

I am currently measuring with the MacOS activity monitor as my valgrind is not working. With valgrind you might want to try:

```bash
valgrind --tool=massif --time-unit=ms ./target/release/axum-leak
ms_print massif.out.765412 >> massif_pretty
```

or simply start program and measure with other programs.

initial memory usage before any requests were executed

![image](https://user-images.githubusercontent.com/98088021/214804662-e179b9f0-9e13-41fc-bfcb-a290fac61bfc.png)

4. Create load

`oha -z 10m -c 500 "http://127.0.0.1:3000/users?username=test"`

I ran it for just some seconds. After stopping the memory usage remains on the higher level:

![image](https://user-images.githubusercontent.com/98088021/214805510-0aff3448-9434-4dac-b2f5-0ad733f1f280.png)

### Code

Cargo.toml
```toml
[package]
name = "axum-leak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
```

main.rs
```rust
use axum::{
    routing::{get, post},
    http::StatusCode,
    response::IntoResponse,
    Json, Router, extract::Query,
};
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;

#[tokio::main]
async fn main() {
    // initialize tracing
    tracing_subscriber::fmt::init();

    // build our application with a route
    let app = Router::new()
        // `GET /` goes to `root`
        .route("/", get(root))
        // `POST /users` goes to `create_user`
        .route("/users", get(create_user));

    // run our app with hyper
    // `axum::Server` is a re-export of `hyper::Server`
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::debug!("listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

// basic handler that responds with a static string
async fn root() -> &'static str {
    "Hello, World!"
}

async fn create_user(
    // this argument tells axum to parse the request body
    // as JSON into a `CreateUser` type
    payload: Query<CreateUser>,
) -> impl IntoResponse {
    // insert your application logic here
    let user = User {
        id: 1337,
        username: payload.username.clone(),
    };

    // this will be converted into a JSON response
    // with a status code of `201 Created`
    (StatusCode::CREATED, Json(user))
}

// the input to our `create_user` handler
#[derive(Deserialize)]
struct CreateUser {
    username: String,
}

// the output to our `create_user` handler
#[derive(Serialize)]
struct User {
    id: u64,
    username: String,
}
```
