### ISSUE TITLE
Dependency clash with axum-extra `cookie` and `cookie-signed` features

### ISSUE THREAD

**Issue by lmammino** [tokio-rs/axum#1831]
Hello, I have been using Axum extra with the `cookie` feature without any issue (works like a charm and I love the interface).

I was not trying to turn my cookies into signed cookies, so I enabled the `cookie-signed` feature.

This lead to Rust stopping compiling the code and providing the following error:

```plain
❯ cargo build
error: failed to select a version for `subtle`.
    ... required by package `digest v0.10.6`
    ... which satisfies dependency `digest = "^0.10.3"` (locked to 0.10.6) of package `hmac v0.12.1`
    ... which satisfies dependency `hmac = "^0.12.0"` of package `cookie v0.17.0`
    ... which satisfies dependency `cookie = "^0.17"` (locked to 0.17.0) of package `axum-extra v0.7.0`
    ... which satisfies dependency `axum-extra = "^0.7.0"` (locked to 0.7.0) of package `backend v0.1.0 (/Users/luciano/Documents/life-foliage-telerilevamento/backend)`
versions that meet the requirements `=2.4` are: 2.4.1, 2.4.0

all possible versions conflict with previously selected packages.

  previously selected package `subtle v2.5.0`
    ... which satisfies dependency `subtle = "^2.3"` (locked to 2.5.0) of package `cookie v0.17.0`
    ... which satisfies dependency `cookie = "^0.17"` (locked to 0.17.0) of package `axum-extra v0.7.0`
    ... which satisfies dependency `axum-extra = "^0.7.0"` (locked to 0.7.0) of package `backend v0.1.0 (/Users/luciano/Documents/life-foliage-telerilevamento/backend)`

failed to select a version for `subtle` which could resolve this conflict
```

This is my current `Cargo.toml`:

```toml
[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
axum = {version="0.6.10", features = ["headers"]}
axum-extra = { version = "0.7.0", features = ["cookie-signed", "cookie"] }
hyper = "0.14.24"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "mysql"] }
thiserror = "1.0.38"
tokio = { version = "1.26.0", features = ["full"] }
tower = "0.4.13"
ulid = { version = "1.0.0", features = ["serde"] }
```

I spent a bit of time trying different combinations of dependencies but I couldn't really figure out a good way to enable the `cookie-signed` feature on `axum-extra`.

Any suggestion on how to try to resolve this would be highly appreciated.

Thanks
