### ISSUE TITLE
tower_http normalize_path middleware behaviour change in axum 0.6.13

### ISSUE THREAD

**Issue by markgoddard** [tokio-rs/axum#1978]
- [x] I have looked for existing issues (including closed) about this

### Version

axum 0.6.13
axum-core 0.3.4

### Platform

`Linux hostname 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

### Crates

axum

### Description

The behaviour of the [normalize_path](https://docs.rs/tower-http/latest/tower_http/normalize_path/index.html) middleware in tower_http changed in axum 0.6.13 compared with 0.6.12.

Reproducer:

Cargo.toml:
```toml
[package]
name = "axum-router-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "=0.6.13"
axum-core = "=0.3.4"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.3", features = ["normalize-path", "trace"] }
```
src/main.rc:
```rust
use axum::{
    routing::get,
    Router,
};
use std::net::SocketAddr;
use tower_http::normalize_path::NormalizePathLayer;

async fn root() -> &'static str {
    "Hello, World!"
}

async fn nested() -> &'static str {
    "Nested!"
}

fn app() -> Router {
    fn v1() -> Router {
        Router::new()
            .route("/nested", get(nested))
    }

    Router::new()
        .route("/", get(root))
        .route("/foo", get(root))
        .nest("/v1", v1())
        .layer(NormalizePathLayer::trim_trailing_slash())
}

#[tokio::main]
async fn main() {
    let app = app();
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

In axum 0.6.12, it's possible to access `/v1/nested` or `/v1/nested/`. In axum 0.6.13, we get 404 with the trailing slash.

While investigating this issue I noticed that in *both* versions of axum, the `/foo` handler cannot be accessed via `/foo/`.

This middleware is quite useful for some clients that automatically add a trailing slash.

I did a little digging, and found that commit 2c2cf361dd7878e3a49a5da5602e7cf37a3b85ee seems to have introduced the change in behaviour. It's quite a large patch, so I didn't look further.
