### ISSUE TITLE
URI extractor behaves differently via HTTP 1 and HTTP 2

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [tokio-rs/axum#2263]
- [x] I have looked for existing issues (including closed) about this

### Version

git commit 8854e660e9ab07404e5bb8e30b92311d3848de05

### Platform

Debian 12 and Windows 10 x64

### Description

When extracting the URI over HTTP 1, axum returns a URI that consists only of a path. When accessing over HTTP/2, it includes the scheme, host, and port too.

Cargo.toml:
```toml
[package]
name = "bug-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.33", features = ["macros", "rt", "rt-multi-thread"] }

[dependencies.axum]
git = "https://github.com/tokio-rs/axum.git"
rev = "8854e660e9ab07404e5bb8e30b92311d3848de05"
default-features = false
features = ["macros", "http1", "http2", "tokio"]

[dependencies.axum-extra]
git = "https://github.com/tokio-rs/axum.git"
rev = "8854e660e9ab07404e5bb8e30b92311d3848de05"
```

main.rs:
```rust
use axum::http::{StatusCode, Uri};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::Router;
use std::net::{Ipv4Addr, SocketAddr};

#[tokio::main]
async fn main() {
    let router = Router::new().route("/", get(hello));

    let addr = SocketAddr::new(Ipv4Addr::LOCALHOST.into(), 7171);
    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();
    axum::serve(listener, router).await.unwrap();
}

async fn hello(uri: Uri) -> Response {
    (StatusCode::OK, uri.to_string()).into_response()
}
```
curl testing:
```
> curl http://127.0.0.1:7171/
/
> curl http://127.0.0.1:7171/ --http2-prior-knowledge
http://127.0.0.1:7171/
```
(also happens in response to browsers, behind a reverse proxy when switching the proxy from http to h2c)

Maybe this is expected? But it certainly surprised me.
