### ISSUE TITLE
Cannot use mutable arguments whenever an axum handler uses the `#[debug_handler]` macro.

### ISSUE THREAD

**Issue by michaelgrigoryan25** [tokio-rs/axum#514]
### Version

```toml
axum-debug = "0.1.0"
axum = { version = "0.3.3", features = ["multipart"] }
```

### Platform
Windows 11 build 21H2, 64-bit

### Crates

```toml
rsa = "0.5.0"
infer = "0.3"
glob = "0.3.0"
rand = "0.8.4"
sha2 = "0.9.8"
hmac = "0.11.0"
tower = "0.4.10"
serde_yaml = "0.8"
futures = "0.3.17"
axum-debug = "0.1.0"
async-trait = "0.1.51"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14.14", features = ["full"] }
axum = { version = "0.3.3", features = ["multipart"] }
tower-http = { version = "0.1.2", features = ["full"] }
```

### Description

There is a bug when using `#[debug_handler]` with `axum`. Whenever I try to add a mutable argument such as:
```rs
pub async fn something(mut multipart: Multipart) -> ....
```

I get the following error:
```shell
error: expected expression, found keyword `mut`
 --> src\somefile.rs
  |
6 | pub async fn handler(mut multipart: Multipart) -> ...
  |                      ^^^ expected expression

error: could not compile `stormi` due to previous error
```

Without the macro everything works fine.
